# Generated by Django 5.2.1 on 2025-05-21 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_si_prenume_reprezentant_legal', models.CharField(max_length=255)),
                ('nume_si_prenume', models.CharField(max_length=255)),
                ('data_nastere', models.DateField()),
                ('greutate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('alergic_la_vreun_medicament', models.BooleanField(default=False)),
                ('la_ce_medicament_este_alergic', models.CharField(blank=True, max_length=255, null=True)),
                ('febra', models.BooleanField(default=False)),
                ('tuse', models.BooleanField(default=False)),
                ('dificultati_respiratorii', models.BooleanField(default=False)),
                ('astenie', models.BooleanField(default=False)),
                ('cefalee', models.BooleanField(default=False)),
                ('dureri_in_gat', models.BooleanField(default=False)),
                ('greturi_varsaturi', models.BooleanField(default=False)),
                ('diaree_constipatie', models.BooleanField(default=False)),
                ('refuzul_alimentatie', models.BooleanField(default=False)),
                ('iritatii_piele', models.BooleanField(default=False)),
                ('nas_infundat', models.BooleanField(default=False)),
                ('rinoree', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoCallPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=100)),
                ('session_type', models.CharField(choices=[('Call', 'Call'), ('Chat', 'Chat'), ('Recommendation', 'Recommendation')], max_length=20)),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('PaymentPending', 'Payment Pending'), ('PaymentCompleted', 'Payment Completed'), ('FormPending', 'Form Pending'), ('FormSubmitted', 'Form Submitted'), ('CallReady', 'Call Ready'), ('CallStarted', 'Call Started'), ('CallEnded', 'Call Ended')], default='Requested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_completed_at', models.DateTimeField(blank=True, null=True)),
                ('form_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('call_started_at', models.DateTimeField(blank=True, null=True)),
                ('call_ended_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_pipelines', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_pipelines', to=settings.AUTH_USER_MODEL)),
                ('questionnaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultation.medicalquestionnaire')),
            ],
            options={
                'indexes': [models.Index(fields=['patient'], name='consultatio_patient_b70abe_idx'), models.Index(fields=['doctor'], name='consultatio_doctor__d2b6a2_idx'), models.Index(fields=['status'], name='consultatio_status_cb5e3d_idx'), models.Index(fields=['session_type'], name='consultatio_session_c6dea5_idx')],
            },
        ),
    ]
