# Generated by Django 5.0.4 on 2025-05-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='videocallpipeline',
            name='consultatio_patient_b70abe_idx',
        ),
        migrations.RemoveIndex(
            model_name='videocallpipeline',
            name='consultatio_doctor__d2b6a2_idx',
        ),
        migrations.RemoveField(
            model_name='videocallpipeline',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='videocallpipeline',
            name='patient',
        ),
        migrations.AddField(
            model_name='videocallpipeline',
            name='doctor_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videocallpipeline',
            name='patient_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='videocallpipeline',
            index=models.Index(fields=['patient_id'], name='consultatio_patient_b70abe_idx'),
        ),
        migrations.AddIndex(
            model_name='videocallpipeline',
            index=models.Index(fields=['doctor_id'], name='consultatio_doctor__d2b6a2_idx'),
        ),
    ]
