# Generated by Django 5.0.4 on 2025-05-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_remove_videocallpipeline_consultatio_patient_b70abe_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocallpipeline',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
