# Generated by Django 5.1.6 on 2025-06-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0003_videocallpipeline_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocallpipeline',
            name='doctor_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='videocallpipeline',
            name='patient_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
