# Generated by Django 5.1.6 on 2025-06-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0004_videocallpipeline_doctor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalquestionnaire',
            name='data_nastere',
            field=models.CharField(max_length=255),
        ),
    ]
